# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7eda026150083f55f57e7e69530b788bbdc9eb2d0fd661d574bca968964ffadd77fdae5213cb0eac76a97ccab7e6b8585130bd7e0173e98185aa1fa3ac95c79

test:
  secret_key_base: a3bf4c14e3447f94c1c4f7dd802fe9b5705d846a3c74db5f5f76b976c634b5e2975d58b8be1313fee7a4b88917e6a0713af9a4f925f8efbbafc36cefdc4eb523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
